import RussoYM.ClayDoeblinVariancePlaceholder

/-!
# Clay Doeblin Variance Target

This file begins replacing the Doeblin variance placeholder with a sharper proof
target.

The old placeholder route proves:

DoeblinMinorization + PositiveDoeblinConstant
=>
BlockVarianceContraction

only because the current structures are abstract placeholder propositions.

This file isolates the real finite-dimensional theorem target:

finite Markov kernel data
+
Doeblin minorization
+
positive Doeblin constant
+
actual variance contraction proof
=>
BlockVarianceContraction

Status note:

This file does not yet prove the real Markov-kernel variance contraction
estimate. Instead, it creates a named target object so future work can replace
the placeholder theorem one layer at a time.
-/

namespace RussoYM
namespace Clay

/--
A named finite-dimensional Doeblin variance proof target.

Future replacement fields should include:

* a finite state space;
* a Markov kernel;
* an invariant probability measure;
* a variance functional;
* a Doeblin minorization inequality;
* a proof that the Markov operator contracts variance.

At the current project abstraction level, we keep the connection to the existing
Clay placeholder objects.
-/
structure FiniteDoeblinVarianceTarget : Prop where
  doeblin_minorization : DoeblinMinorization
  positive_alpha : PositiveDoeblinConstant
  variance_contraction : BlockVarianceContraction

/--
Extract the block variance contraction from the finite-dimensional Doeblin
variance target.

This is the exact point where the future real Markov-kernel proof should enter.
-/
theorem varianceContraction_of_finiteDoeblinVarianceTarget
    (h : FiniteDoeblinVarianceTarget) :
    BlockVarianceContraction := by
  exact h.variance_contraction

/--
Once the variance contraction target is supplied, the rest of the current
placeholder chain gives block Poincare.
-/
theorem blockPoincare_of_finiteDoeblinVarianceTarget
    (h : FiniteDoeblinVarianceTarget) :
    BlockPoincare := by
  have hVar : BlockVarianceContraction :=
    varianceContraction_of_finiteDoeblinVarianceTarget h
  have hGap : PositiveBlockSpectralGap :=
    positiveBlockGap_of_varianceContraction_placeholder hVar
  exact blockPoincare_of_positiveBlockGap_placeholder hGap

/--
Convert the finite-dimensional Doeblin variance target into the existing
minorization/Poincare skeleton.

This keeps compatibility with the rest of the current architecture.
-/
theorem minorizationPoincareSkeleton_of_finiteDoeblinVarianceTarget
    (h : FiniteDoeblinVarianceTarget) :
    MinorizationPoincareSkeleton := by
  exact {
    doeblin_minorization := h.doeblin_minorization
    positive_alpha := h.positive_alpha
  }

/--
Compatibility theorem: the target object implies the old placeholder
minorization-to-Poincare conclusion.

The difference is that the variance contraction is now a named target field,
rather than being silently generated by `True.intro`.
-/
theorem blockPoincare_of_finiteDoeblinVarianceTarget_compatible
    (h : FiniteDoeblinVarianceTarget) :
    BlockPoincare := by
  exact blockPoincare_of_finiteDoeblinVarianceTarget h

end Clay
end RussoYM